id: CVE Exposure - RiskSense
version: -1
name: CVE Exposure - RiskSense
description: Block IPs and apply the tag to assets that are vulnerable to the specified CVE.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 0c2f9026-080c-4894-8d97-98e4d8756703
    type: start
    task:
      id: 0c2f9026-080c-4894-8d97-98e4d8756703
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: 'start'
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -210,
          "y": 30
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    continueonerrortype: ""
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 5c12e6b5-bebc-4667-845d-eeb7d826155a
    type: condition
    task:
      id: 5c12e6b5-bebc-4667-845d-eeb7d826155a
      version: -1
      name: Is RiskSense enabled?
      description: Returns 'yes' if RiskSense is enabled. Otherwise returns 'no'.
      scriptName: IsIntegrationAvailable
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "10"
      "yes":
      - "18"
    scriptarguments:
      brandname:
        simple: RiskSense
    results:
    - brandInstances
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -210,
          "y": 170
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    continueonerrortype: ""
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: e1a7f22d-c964-4537-80f8-c71c9ee58cd1
    type: regular
    task:
      id: e1a7f22d-c964-4537-80f8-c71c9ee58cd1
      version: -1
      name: Apply tag to found assets
      description: Apply the new or existing tag to the asset, or creates a new tag if the tag does not exist in RiskSense.
      script: '|||risksense-apply-tag'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "16"
    scriptarguments:
      assettype:
        simple: host
      fieldname:
        simple: id
      operator:
        simple: IN
      tagname:
        complex:
          root: inputs.TagName
      value:
        complex:
          root: RiskSense
          accessor: HostFinding.HostID
          transformers:
          - operator: uniq
          - operator: Stringify
          - operator: join
            args:
              separator:
                value:
                  simple: ','
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 440,
          "y": 990
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    continueonerrortype: ""
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: 7c77c3b8-f938-4e1d-81d7-9c04db2847fb
    type: title
    task:
      id: 7c77c3b8-f938-4e1d-81d7-9c04db2847fb
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: 'Done'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -210,
          "y": 1380
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    continueonerrortype: ""
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: 936bdd54-0740-4e4c-869c-84f8bb82487c
    type: regular
    task:
      id: 936bdd54-0740-4e4c-869c-84f8bb82487c
      version: -1
      name: Get open findings related to CVEs
      description: A detailed host finding view with the severity level. Displays vulnerability information like CVE, threats associated with current findings, and origin of findings.
      script: '|||risksense-get-host-findings'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      fieldname:
        simple: cves
      operator:
        simple: IN
      size:
        simple: "1000"
      sort_by:
        simple: Risk Rating
      sort_direction:
        simple: Descending
      status:
        simple: Open
      value:
        complex:
          root: inputs.CVES
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 180,
          "y": 640
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    continueonerrortype: ""
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: 4f42421d-9238-4871-8d95-48ef34cc08ae
    type: condition
    task:
      id: 4f42421d-9238-4871-8d95-48ef34cc08ae
      version: -1
      name: Are asset findings found?
      description: Returns 'yes' if asset findings found. Otherwise returns 'no'
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "10"
      "yes":
      - "6"
      - "14"
      - "15"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: RiskSense.HostFinding.ID
            iscontext: true
    view: |-
      {
        "position": {
          "x": 180,
          "y": 800
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    continueonerrortype: ""
    isoversize: false
    isautoswitchedtoquietmode: false
  "13":
    id: "13"
    taskid: 9f36553b-2b15-4a90-85e0-65c486068d89
    type: title
    task:
      id: 9f36553b-2b15-4a90-85e0-65c486068d89
      version: -1
      name: Get assets findings with the asset and perform actions
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "11"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 180,
          "y": 510
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    continueonerrortype: ""
    isoversize: false
    isautoswitchedtoquietmode: false
  "14":
    id: "14"
    taskid: 8023da73-46df-44a8-8355-9876a09da604
    type: title
    task:
      id: 8023da73-46df-44a8-8355-9876a09da604
      version: -1
      name: Blocks IP addresses (requires at least one integration)
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "17"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 850,
          "y": 990
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    continueonerrortype: ""
    isoversize: false
    isautoswitchedtoquietmode: false
  "15":
    id: "15"
    taskid: ea128f99-f05a-47c6-8893-1c42fa831a2a
    type: regular
    task:
      id: ea128f99-f05a-47c6-8893-1c42fa831a2a
      version: -1
      name: Get asset information with owner
      description: Gets details of the supplied host. The host details can be searched based on input parameters like fieldname (Host Name, IP Address, Criticality, etc), operator (EXACT, IN, LIKE, BETWEEN), page, size, sort by, and sort direction.
      script: '|||risksense-get-hosts'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      fieldname:
        simple: id
      operator:
        simple: IN
      size:
        simple: "1000"
      sort_by:
        simple: RS3
      sort_direction:
        simple: Descending
      value:
        complex:
          root: RiskSense
          accessor: HostFinding.HostID
          transformers:
          - operator: uniq
          - operator: Stringify
          - operator: join
            args:
              separator:
                value:
                  simple: ','
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 40,
          "y": 990
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    continueonerrortype: ""
    isoversize: false
    isautoswitchedtoquietmode: false
  "16":
    id: "16"
    taskid: 4083fb31-386a-4e65-8a14-78b53786244d
    type: regular
    task:
      id: 4083fb31-386a-4e65-8a14-78b53786244d
      version: -1
      name: Apply tag to found asset findings
      description: Apply the new or existing tag to the asset, or creates a new tag if it does not exist in RiskSense.
      script: '|||risksense-apply-tag'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      assettype:
        simple: hostFinding
      fieldname:
        simple: id
      operator:
        simple: IN
      tagname:
        complex:
          root: inputs.TagName
      value:
        complex:
          root: RiskSense
          accessor: HostFinding.ID
          transformers:
          - operator: uniq
          - operator: Stringify
          - operator: join
            args:
              separator:
                value:
                  simple: ','
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 440,
          "y": 1165
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    continueonerrortype: ""
    isoversize: false
    isautoswitchedtoquietmode: false
  "17":
    id: "17"
    taskid: b31a916a-9752-45fb-8354-5856a5124be6
    type: playbook
    task:
      id: b31a916a-9752-45fb-8354-5856a5124be6
      version: -1
      name: Block IP - Generic v2
      playbookName: Block IP - Generic v2
      type: playbook
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      AutoCommit:
        simple: "No"
      CustomBlockRule:
        simple: "True"
      IP:
        complex:
          root: RiskSense
          accessor: HostFinding.HostIpAddress
          transformers:
          - operator: uniq
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 850,
          "y": 1165
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    continueonerrortype: ""
    isoversize: false
    isautoswitchedtoquietmode: false
  "18":
    id: "18"
    taskid: 6593a27e-f010-4f9c-8250-6f7744cd3a08
    type: condition
    task:
      id: 6593a27e-f010-4f9c-8250-6f7744cd3a08
      version: -1
      name: Are Inputs provided?
      description: Returns 'yes' if inputs are provided. Otherwise returns 'no'.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "10"
      "yes":
      - "13"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              complex:
                root: inputs.CVE_ID
            iscontext: true
          right:
            value: {}
      - - operator: isNotEmpty
          left:
            value:
              complex:
                root: inputs.TagName
            iscontext: true
    view: |-
      {
        "position": {
          "x": 0,
          "y": 340
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    continueonerrortype: ""
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {
      "12_10_#default#": 0.46,
      "12_15_yes": 0.76,
      "18_10_#default#": 0.1,
      "18_13_yes": 0.64,
      "1_10_#default#": 0.19
    },
    "paper": {
      "dimensions": {
        "height": 1415,
        "width": 1440,
        "x": -210,
        "y": 30
      }
    }
  }
inputs:
- key: CVE_ID
  value: {}
  required: true
  description: "Specify Common Vulnerabilities and Exposures (CVE). \nSeparate multiple search values by commas only (without spaces or any special characters)."
  playbookInputQuery:
- key: TagName
  value: {}
  required: true
  description: Tags in RiskSense can be applied to assets, web applications, and vulnerabilities. Tags are useful in the soft grouping, workflow creation and to identify compliance-related assets.
  playbookInputQuery:
outputs:
- contextPath: RiskSense.TagAssociation
  description: Tag association details including tag name, association ID, created.
  type: unknown
- contextPath: RiskSense.HostFinding
  description: List of the host finding details.
  type: unknown
- contextPath: RiskSense.Host
  description: List of the host details.
  type: unknown
fromversion: 5.0.0
tests:
- No tests (auto formatted)
contentitemexportablefields:
  contentitemfields: {}
