id: Search all mailboxes - Gmail
version: -1
name: Search all mailboxes - Gmail
description: This playbook searches Gmail records for all Google users, designed for large companies with over 500 Google users.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: cf6bc2b4-cafb-4eb8-8d70-93ccb3bf8f75
    type: start
    task:
      id: cf6bc2b4-cafb-4eb8-8d70-93ccb3bf8f75
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 8b33d229-bc7c-46d2-80b0-3487035cce4e
    type: playbook
    task:
      id: 8b33d229-bc7c-46d2-80b0-3487035cce4e
      version: -1
      name: Search in mailboxes Gmail (Loop)
      description: This playbook is used as a subplaybook for the Playbook Search-all-mailboxes - Gmail, it should not be used.
      playbookName: Search in mailboxes Gmail (Loop)
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      after:
        complex:
          root: inputs.after
      before:
        complex:
          root: inputs.before
      fields:
        complex:
          root: inputs.fields
      filename:
        complex:
          root: inputs.filename
      from:
        complex:
          root: inputs.from
      has-attachments:
        complex:
          root: inputs.has-attachments
      in:
        complex:
          root: inputs.in
      include-spam-trash:
        complex:
          root: inputs.include-spam-trash
      labels-ids:
        complex:
          root: inputs.labels-ids
      max-results:
        complex:
          root: inputs.max-results
      page-token:
        complex:
          root: NewPageToken
      query:
        complex:
          root: inputs.query
      show-only-mailboxes:
        complex:
          root: inputs.show-only-mailboxes
      subject:
        complex:
          root: inputs.subject
      to:
        complex:
          root: inputs.to
    separatecontext: false
    continueonerrortype: ""
    loop:
      iscommand: false
      builtincondition:
      - - operator: isEqualString
          left:
            value:
              simple: ${Stop}
            iscontext: true
          right:
            value:
              simple: "true"
      exitCondition: ""
      wait: 5
      max: 100
    view: |-
      {
        "position": {
          "x": 50,
          "y": 205
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 2
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: d9b8ff21-a8ec-437b-8d5e-2af99e27d119
    type: title
    task:
      id: d9b8ff21-a8ec-437b-8d5e-2af99e27d119
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: ddaba651-7bad-422f-8cee-daeac88d878b
    type: regular
    task:
      id: ddaba651-7bad-422f-8cee-daeac88d878b
      version: -1
      name: DeleteContext
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-2/cortex-xsoar-admin/playbooks/automations.html
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all:
        simple: "yes"
      keysToKeep:
        simple: Gmail
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 560,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: after
  value: {}
  required: false
  description: Search for messages sent after a certain time period. For example, 2018/05/06
  playbookInputQuery:
- key: before
  value: {}
  required: false
  description: Search for messages sent before a certain time period. For example, 2018/05/09
  playbookInputQuery:
- key: fields
  value: {}
  required: false
  description: Enables partial responses to be retrieved in a comma separated list. For more information, see https://developers.google.com/gdata/docs/2.0/basics#PartialResponse.
  playbookInputQuery:
- key: filename
  value: {}
  required: false
  description: Attachments with a certain name or file type. For example, "pdf" or "report.pdf"
  playbookInputQuery:
- key: from
  value: {}
  required: false
  description: Specifies the sender. For example, "john"
  playbookInputQuery:
- key: to
  value: {}
  required: false
  description: Specifies the receiver. For example, "john"
  playbookInputQuery:
- key: has-attachments
  value: {}
  required: false
  description: Whether to search for messages sent with attachments.
  playbookInputQuery:
- key: in
  value: {}
  required: false
  description: Messages in any folder, including Spam and Trash. For example, shopping
  playbookInputQuery:
- key: include-spam-trash
  value: {}
  required: false
  description: 'Includes messages from SPAM and TRASH in the results. (Default: false)'
  playbookInputQuery:
- key: labels-ids
  value: {}
  required: false
  description: Only returns messages with labels that match all of the specified label IDs in a comma separated list.
  playbookInputQuery:
- key: show-only-mailboxes
  value: {}
  required: false
  description: Whether to return only mailboxes which contain the email. Default is "True".
  playbookInputQuery:
- key: subject
  value: {}
  required: false
  description: Words in the subject line. For example, "alert"
  playbookInputQuery:
- key: query
  value: {}
  required: false
  description: 'Returns messages matching the specified query. Supports the same query format as the Gmail search box. For example, "from:someuser@example.com rfc822msgid: is:unread". For more syntax information,see "https://support.google.com/mail/answer/7190?hl=en"'
  playbookInputQuery:
- key: max-results
  value: {}
  required: false
  description: |-
    The maximum number of results to return per user. Default is 100. Maximum is 500. Acceptable values are 1 to 500, inclusive.
    (Used in the case that show-only-mailboxes argument is false)
  playbookInputQuery:
outputs:
- contextPath: Gmail.Mailboxes
  description: The Gmail Mailbox.
- contextPath: Gmail.ID
  description: Inner ID of the Gmail message.
- contextPath: Gmail.ThreadId
  description: The thread ID.
- contextPath: Gmail.Format
  description: MIME type of the email.
- contextPath: Gmail.Labels
  description: Labels of a specific email.
- contextPath: Gmail.To
  description: Email Address of the receiver.
- contextPath: Gmail.From
  description: Email Address of the sender.
- contextPath: Gmail.Cc
  description: Additional recipient email address (CC).
- contextPath: Gmail.Bcc
  description: Additional recipient email address (BCC).
- contextPath: Gmail.Subject
  description: Subject of the specific email.
- contextPath: Gmail.Body
  description: The content of the email.
- contextPath: Gmail.Attachments
  description: The attachments of the email. IDs are separated by ','.
- contextPath: Gmail.Headers
  description: All headers of specific mail (list).
tests:
- Gmail Convert Html Test
fromversion: 6.5.0
