id: Search Endpoint by CVE - Generic
version: -1
name: Search Endpoint by CVE - Generic
description: Hunt for assets with a given CVE using available tools
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 3cc9f67a-3dcb-4793-8ac2-fbbeac13430c
    type: start
    task:
      id: 3cc9f67a-3dcb-4793-8ac2-fbbeac13430c
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -320,
          "y": -310
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    continueonerrortype: ""
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 50599a6e-469f-4e76-8053-7401f03f00e9
    type: condition
    task:
      id: 50599a6e-469f-4e76-8053-7401f03f00e9
      version: -1
      name: Is there CVE?
      description: Checks if there is a CVE in the playbook input.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "19"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              complex:
                root: inputs.CVE_ID
            iscontext: true
          right:
            value: {}
    view: |-
      {
        "position": {
          "x": -320,
          "y": -160
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    continueonerrortype: ""
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 5c6efc1c-e322-4f05-875b-e1e9410adf25
    type: title
    task:
      id: 5c6efc1c-e322-4f05-875b-e1e9410adf25
      version: -1
      name: Search CVE
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "3"
      - "7"
      - "13"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 400,
          "y": 180
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    continueonerrortype: ""
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 776c24cb-8546-4e9c-81f7-cfd2dc6c4727
    type: title
    task:
      id: 776c24cb-8546-4e9c-81f7-cfd2dc6c4727
      version: -1
      name: Rapid7 Nexpose
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -50,
          "y": 340
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    continueonerrortype: ""
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 7ac9c77b-61c0-4f56-8bfe-0e9a3bef8561
    type: condition
    task:
      id: 7ac9c77b-61c0-4f56-8bfe-0e9a3bef8561
      version: -1
      name: Is Rapid7 Nexpose (InsightVM) enabled?
      description: 'Returns ''yes'' if integration brand is available. Otherwise returns ''no'''
      type: condition
      iscommand: false
      brand: ""
      scriptName: IsIntegrationAvailable
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "5"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -50,
          "y": 475
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    scriptarguments:
      brandname:
        simple: Rapid7 InsightVM
    results:
    - brandInstances
    continueonerrortype: ""
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 7d237b3e-0c1e-4110-8f88-2defb0aec7f3
    type: regular
    task:
      id: 7d237b3e-0c1e-4110-8f88-2defb0aec7f3
      version: -1
      name: 'Search CVE with Rapid7 Nexpose '
      description: Returns all assets for which you have access that match the given search criteria.
      tags:
      - autoCVEsearch
      script: Rapid7 Nexpose|||nexpose-search-assets
      type: regular
      iscommand: true
      brand: Rapid7 Nexpose
    nexttasks:
      '#none#':
      - "21"
    scriptarguments:
      vulnerabilityTitleContains:
        complex:
          root: CVE_IDParsed
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -50,
          "y": 710
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    fieldMapping:
    - incidentfield: Breached Compromised Hosts
      output:
        complex:
          root: Nexpose
          accessor: Asset
          transformers:
          - operator: ConvertToSingleElementArray
    skipunavailable: true
    quietmode: 0
    continueonerrortype: ""
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: 77c6e21a-e184-4f3e-8f5f-66b2eae4bbdf
    type: condition
    task:
      id: 77c6e21a-e184-4f3e-8f5f-66b2eae4bbdf
      version: -1
      name: Is Kennav2 enabled?
      description: 'Returns ''yes'' if integration brand is available. Otherwise returns ''no'''
      type: condition
      iscommand: false
      brand: ""
      scriptName: IsIntegrationAvailable
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "8"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 860,
          "y": 475
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    scriptarguments:
      brandname:
        simple: Kenna v2
    results:
    - brandInstances
    continueonerrortype: ""
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: 4dcb3885-0d0e-4dd8-8a6d-744a3c57b9b8
    type: title
    task:
      id: 4dcb3885-0d0e-4dd8-8a6d-744a3c57b9b8
      version: -1
      name: Kennav2
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "6"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 860,
          "y": 340
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    continueonerrortype: ""
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: 247ca7fb-7ac8-4cdb-81cb-13f9fc9e37e8
    type: regular
    task:
      id: 247ca7fb-7ac8-4cdb-81cb-13f9fc9e37e8
      version: -1
      name: Search CVE with Kenna
      description: Searches for vulnerabilities in Kenna.
      tags:
      - autoCVEsearch
      script: '|||kenna-search-vulnerabilities'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      id:
        complex:
          root: CVE_IDParsed
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 860,
          "y": 710
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: true
    quietmode: 0
    continueonerrortype: ""
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: ae99de5a-7c26-4cf6-87fc-d004af1cb212
    type: title
    task:
      id: ae99de5a-7c26-4cf6-87fc-d004af1cb212
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -320,
          "y": 1380
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    continueonerrortype: ""
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: cffb6924-0a75-4ed9-89d3-33944c6d31b2
    type: condition
    task:
      id: cffb6924-0a75-4ed9-89d3-33944c6d31b2
      version: -1
      name: Found results?
      description: If found Assets with the given CVE
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "12"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: Kenna
                accessor: Vulnerabilities
            iscontext: true
    view: |-
      {
        "position": {
          "x": 860,
          "y": 875
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    continueonerrortype: ""
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: 5dc657f4-1a09-4466-87e0-c4e6aa568d3c
    type: regular
    task:
      id: 5dc657f4-1a09-4466-87e0-c4e6aa568d3c
      version: -1
      name: Get hostname from assetID
      description: Searches for assets.
      script: '|||kenna-search-assets'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "18"
    scriptarguments:
      id:
        complex:
          root: Kenna.Vulnerabilities
          accessor: AssetID
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1130,
          "y": 1050
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    fieldMapping:
    - incidentfield: Breached Compromised Hosts
      output:
        complex:
          root: Kenna
          accessor: Assets
    skipunavailable: false
    quietmode: 0
    continueonerrortype: ""
    isoversize: false
    isautoswitchedtoquietmode: false
  "13":
    id: "13"
    taskid: 536cbf27-e426-49ec-8746-d74a6912cf81
    type: title
    task:
      id: 536cbf27-e426-49ec-8746-d74a6912cf81
      version: -1
      name: RiskSense
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "14"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 400,
          "y": 340
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    continueonerrortype: ""
    isoversize: false
    isautoswitchedtoquietmode: false
  "14":
    id: "14"
    taskid: 44fb00a5-4908-40ea-87d8-f3c3956941e3
    type: condition
    task:
      id: 44fb00a5-4908-40ea-87d8-f3c3956941e3
      version: -1
      name: 'Is RiskSense Enabled? '
      description: 'Returns ''yes'' if integration brand is available. Otherwise returns ''no'''
      type: condition
      iscommand: false
      brand: ""
      scriptName: IsIntegrationAvailable
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "20"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 400,
          "y": 475
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    scriptarguments:
      brandname:
        simple: RiskSense
    results:
    - brandInstances
    continueonerrortype: ""
    isoversize: false
    isautoswitchedtoquietmode: false
  "17":
    id: "17"
    taskid: 80eb5dc1-31a1-4265-8c8e-50a4df6027df
    type: regular
    task:
      id: 80eb5dc1-31a1-4265-8c8e-50a4df6027df
      version: -1
      name: Set results to Endpoint context
      description: Set a value in context under the key you entered. If no value is entered, the script doesn't do anything.
      scriptName: SetAndHandleEmpty
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: Endpoint
      value:
        complex:
          root: RiskSense.Host
          filters:
          - - operator: isNotEmpty
              left:
                value:
                  simple: RiskSense.Host
                iscontext: true
          transformers:
          - operator: uniq
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 400,
          "y": 875
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    continueonerrortype: ""
    isoversize: false
    isautoswitchedtoquietmode: false
  "18":
    id: "18"
    taskid: 26bb49f2-7b1b-4705-8491-2fab5656fd2e
    type: regular
    task:
      id: 26bb49f2-7b1b-4705-8491-2fab5656fd2e
      version: -1
      name: Set results to Endpoint context
      description: Set a value in context under the key you entered. If no value is entered, the script doesn't do anything.
      scriptName: SetAndHandleEmpty
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: Endpoint
      value:
        complex:
          root: Kenna.Assets.Hostname
          filters:
          - - operator: isNotEmpty
              left:
                value:
                  simple: Kenna.Assets.Hostname
                iscontext: true
          transformers:
          - operator: uniq
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1130,
          "y": 1210
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    continueonerrortype: ""
    isoversize: false
    isautoswitchedtoquietmode: false
  "19":
    id: "19"
    taskid: e77b5b38-ca0b-4495-865f-4aac903b6dee
    type: playbook
    task:
      id: e77b5b38-ca0b-4495-865f-4aac903b6dee
      version: -1
      name: Threat Hunting - Set Indicators
      description: "This playbook normalizes a variety of indicators to facilitate their use within threat hunting and detection playbooks, as well as reduce the possibility of task errors.\nUsing this playbook as a sub-playbook in threat hunting and detection playbooks is particularly useful if inputs are manually entered.\n\nThe playbook removes duplications, splits each input into an array of strings, and then stores the indicators under newly created context keys.\n\nNote that multiple search values should be separated by commas only (without spaces or any special characters). \n\nSupported IOCs for this playbook:\n- MD5\n- SHA1\n- SHA256\n- IP Address\n- URLDomain\n- Registry Value\n- Registry Key\n- Registry Hives\n- Command Line\n- File Name\n- Process Name\n- HTTP Request Methods\n- User Agent\n- Port Number\n- File Path\n- Geolocation\n- Email Address\n- CIDR\n- URI\n- Ja3\n- FileType"
      playbookName: Threat Hunting - Set Indicators
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      CVE_ID:
        complex:
          root: inputs.CVE_ID
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 0,
          "y": 10
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: true
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "20":
    id: "20"
    taskid: 71623d4d-562a-49ca-8083-8c49cd02d5b9
    type: playbook
    task:
      id: 71623d4d-562a-49ca-8083-8c49cd02d5b9
      version: -1
      name: CVE Exposure - RiskSense
      playbookName: CVE Exposure - RiskSense
      type: playbook
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "17"
    scriptarguments:
      CVE_ID:
        complex:
          root: inputs.CVE_ID
          transformers:
          - operator: uniq
      TagName:
        simple: FireEye RedTeam tools
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 400,
          "y": 710
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "21":
    id: "21"
    taskid: a8a27af5-6162-40b4-8f65-b2806c71572c
    type: regular
    task:
      id: a8a27af5-6162-40b4-8f65-b2806c71572c
      version: -1
      name: Set results to Endpoint context
      description: Set a value in context under the key you entered. If no value is entered, the script doesn't do anything.
      scriptName: SetAndHandleEmpty
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: Endpoint
      value:
        complex:
          root: Endpoint.HostName
          filters:
          - - operator: isNotEmpty
              left:
                value:
                  simple: Endpoint.HostName
                iscontext: true
          transformers:
          - operator: uniq
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": -50,
          "y": 875
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {
      "11_12_yes": 0.68,
      "11_9_#default#": 0.1,
      "14_20_yes": 0.56,
      "14_9_#default#": 0.19,
      "1_19_yes": 0.57,
      "1_9_#default#": 0.13,
      "4_5_yes": 0.49,
      "4_9_#default#": 0.27,
      "6_8_yes": 0.53,
      "6_9_#default#": 0.14
    },
    "paper": {
      "dimensions": {
        "height": 1755,
        "width": 1830,
        "x": -320,
        "y": -310
      }
    }
  }
inputs:
- key: CVE_ID
  value: {}
  required: false
  description: |-
    Hunt for assets with a given CVE using available tools.
    Separate multiple search values by commas only (without spaces or any special characters).
  playbookInputQuery:
outputs:
- contextPath: Kenna.Assets
  description: Compromised Assets retrieved from Kenna.
  type: unknown
- contextPath: Nexpose.Asset
  description: Compromised Assets retrieved from Nexpose.
  type: unknown
- contextPath: Endpoint
  description: Global compromised Assets
  type: unknown
- contextPath: RiskSense.Host
  description: Compromised Assets retrieved from RiskSense.
  type: unknown
tests:
- No tests (auto formatted)
fromversion: 5.5.0
contentitemexportablefields:
  contentitemfields: {}
