id: Azure SecurityCenter - Test
version: -1
name: Azure SecurityCenter - Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 4b1d827a-ab81-41e7-882f-0cd6986d629b
    type: start
    task:
      id: 4b1d827a-ab81-41e7-882f-0cd6986d629b
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: d0a0afb0-de7c-4fd8-8d01-66b1caeb616b
    type: regular
    task:
      id: d0a0afb0-de7c-4fd8-8d01-66b1caeb616b
      version: -1
      name: azure-sc-list-aps
      description: Lists auto provisioning settings in the subscription.
      script: '|||azure-sc-list-aps'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: e470784b-6f0d-4774-85a6-2662de70811d
    type: regular
    task:
      id: e470784b-6f0d-4774-85a6-2662de70811d
      version: -1
      name: azure-sc-get-aps
      description: Returns details of a specific auto provisioning setting.
      script: '|||azure-sc-get-aps'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      setting_name:
        simple: ${AzureSecurityCenter.AutoProvisioningSetting.Name}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 89f91ff0-a26a-4be3-85d9-18f38f8b303d
    type: regular
    task:
      id: 89f91ff0-a26a-4be3-85d9-18f38f8b303d
      version: -1
      name: azure-sc-list-alert
      description: Lists alerts for the subscription according to the specified filters.
      script: '|||azure-sc-list-alert'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      asc_location:
        simple: centralus
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 15394a33-9884-4402-8559-30dd38b7bbf6
    type: regular
    task:
      id: 15394a33-9884-4402-8559-30dd38b7bbf6
      version: -1
      name: azure-sc-list-jit
      description: Lists all policies for protecting resources using Just-in-Time
        access control.
      script: '|||azure-sc-list-jit'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1035
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 85d65fbf-0fc3-434c-849f-78a63056a174
    type: regular
    task:
      id: 85d65fbf-0fc3-434c-849f-78a63056a174
      version: -1
      name: azure-sc-list-location
      description: The location of the responsible ASC of the specific subscription.
        For each subscription there is only one responsible location.
      script: '|||azure-sc-list-location'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1210
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: fefe1a7a-8dc8-46d5-8aa1-13010e9095a0
    type: regular
    task:
      id: fefe1a7a-8dc8-46d5-8aa1-13010e9095a0
      version: -1
      name: azure-sc-list-storage
      description: Lists all the storage accounts available under the subscription.
      script: '|||azure-sc-list-storage'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1385
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: fc9fe2d0-ad2c-4ba8-8d00-948b3d1ad01a
    type: regular
    task:
      id: fc9fe2d0-ad2c-4ba8-8d00-948b3d1ad01a
      version: -1
      name: azure-sc-update-aps
      description: Updates a specific auto provisioning setting.
      script: '|||azure-sc-update-aps'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      auto_provision:
        simple: "Off"
      setting_name:
        simple: default
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1560
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: d02710a7-17ff-4058-8821-45b72c29c7c8
    type: regular
    task:
      id: d02710a7-17ff-4058-8821-45b72c29c7c8
      version: -1
      name: azure-list-subscriptions
      description: Lists available subscriptions for this application.
      script: '|||azure-list-subscriptions'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1735
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: a6adf7cc-361d-4643-8ea6-891ba05b17fb
    type: regular
    task:
      id: a6adf7cc-361d-4643-8ea6-891ba05b17fb
      version: -1
      name: azure-sc-get-alert
      description: Get an alert that is associated a resource group or a subscription.
      script: '|||azure-sc-get-alert'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      alert_id:
        complex:
          root: AzureSecurityCenter.Alert
          accessor: ID
          transformers:
          - operator: FirstArrayElement
      asc_location:
        simple: centralus
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 870
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: a419e7b3-a9f0-46ff-8431-86fb4aa7fa18
    type: regular
    task:
      id: a419e7b3-a9f0-46ff-8431-86fb4aa7fa18
      version: -1
      name: azure-get-secure-score
      description: Retrieve the Secure Score for the provided subscription and score
        name
      script: '|||azure-get-secure-score'
      type: regular
      iscommand: true
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1900
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: 021c974c-6524-474b-85cd-991186266d42
    type: condition
    task:
      id: 021c974c-6524-474b-85cd-991186266d42
      version: -1
      name: Is List empty?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "4"
    separatecontext: false
    defaultassigneecomplex:
      simple: ${AzureSecurityCenter.Alert}
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotExists
          left:
            value:
              simple: AzureSecurityCenter.Alert
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 700
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1945,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
fromversion: 5.0.0
description: ''
