name: Docker Update Auto Merge
on:
  pull_request:
  schedule:
    - cron: '50 18 * * *'
    - cron: '52 18 * * *'

permissions:
  pull-requests: write
  contents: write

jobs:
  auto_approve_and_merge:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'demisto/') && github.repository == 'demisto/content' && contains(github.event.pull_request.labels.*.name, 'docker')
    steps:
      - name: Print out event stuff
        run: |
          echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
      - name: Check if build passed
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Checks CI Status"
          gh pr checks --required "$PR_URL"
      - name: Approve and auto-merge for docker update PRs
        if: ${{ success() }}
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          CONTENTBOT_GH_ADMIN_TOKEN: ${{ secrets.CONTENTBOT_GH_ADMIN_TOKEN }}
        run: |
          echo "Approving and merging"
          gh pr review --approve "$PR_URL"
