name: pre-commit
on: pull_request

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install demisto-sdk
      run: pip install git+https://github.com/demisto/demisto-sdk@9361b13f1684abaaa6ea0424a2e279d350a2b6b2
    
    # - uses: actions/cache@v3
    #   with:
    #     path: ~/.cache/pre-commit
    #     key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}

    - name: run pre-commit
      run: demisto-sdk pre-commit -g --test
