name: pre-commit
on: pull_request

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Install poetry
      run: pipx install poetry

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup python
    
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'poetry'
    - name: Install dependencies
      run: poetry install
    
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-3|${{ env.pythonLocation }}

    - name: run pre-commit
      run: demisto-sdk pre-commit -g --test
