name: pre-commit
on: pull_request

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install demisto-sdk
      run: pip install git+https://github.com/demisto/demisto-sdk@6720cd52c31971fb77801bf523a4c5553b96dc9a
    - name: run pre-commit
      run: demisto-sdk pre-commit -g --test
