name: pre-commit
on: pull_request

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install demisto-sdk
      run: pip install demisto-sdk
    - name: run pre-commit
      run: demisto-sdk pre-commit -g
