name: Review Release Notes
on: pull_request

env:
  CHANGED_FILES_DELIMITER: ","

jobs:
  release_notes_review:
    runs-on: ubuntu-latest
    if: github.repository == 'demisto/content' && github.event.pull_request.head.repo.fork == false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35.1.0
        with:
          separator: ${{ env.CHANGED_FILES_DELIMITER }}
          files: |
            Packs/**/ReleaseNotes/**
          since_last_remote_commit: false
      # - name: Install poetry
      #   run: pipx install poetry
      # - name: Setup Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.10.6'
      #     cache: 'poetry'
      # - name: Install Python dependencies
      #   run: poetry install --without linters,testing,typing,ci --no-root

      - name: Install SDK
        run: python3 -m pip install demisto-sdk

      - name: Review Release Notes
        run: |
          release_notes="${{ steps.changed-files.outputs.all_changed_files }}"

          if [ ! -z "$release_notes" -a "$release_notes" != " " ]; then
            echo "Release notes found in PR: ${release_notes}"
            release_notes_to_review=$(Utils/github_workflow_scripts/get_xsoar_supported_release_notes.py "$release_notes" --delimiter ${{ env.CHANGED_FILES_DELIMITER }}) 

            # Check if there are any release notes
            if [ ! -z "$release_notes_to_review" -a "$release_notes_to_review" != " " ]; then

              echo "Release notes requiring review: $release_notes_to_review"
              
              echo "Starting docs review..."
              Utils/github_workflow_scripts/run_docs_review.py --changed_files "$release_notes_to_review" --delimiter ${{ env.CHANGED_FILES_DELIMITER }}
              
              echo "Finished docs review successfully"
            else
              echo "No need to run doc review. Exiting..."
            fi
          else
            echo "No need to run doc review. Exiting..."
          fi


