name: Review Release Notes
on: pull_request

env:
  CHANGED_FILES_DELIMITER: ","

jobs:
  release_notes_review:
    runs-on: ubuntu-latest
    if: github.repository == 'demisto/content' && github.event.pull_request.head.repo.fork == false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v18.7
        with:
          separator: ${{ env.CHANGED_FILES_DELIMITER }}
          files: |
            Packs/**/ReleaseNotes/**
            Packs/**/pack_metadata.json
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v7
      - name: Install Python Dependencies
        run: |
          poetry install --with ci
      - name: Review Release Notes
        run: |
          changed_files="${{ steps.changed-files.outputs.all_changed_files }}"
          for file in "$changed_files"; do
            echo "File '${file}' was changed"
          done;
          echo "Starting docs review..."
          poetry run python Utils/github_workflow_scripts/run_docs_review.py --changed_files "$changed_files" --delimiter ${{ env.CHANGED_FILES_DELIMITER }}
          echo "Finished docs review successfully"